### ISSUE TITLE
As a student using NodeBB, I want to see a list of my classes so that I can go to a Q/A for any of them.

### ISSUE THREAD

**Issue by Fakpabio** [CMU-313/fall23-nodebb-fam#3] opened 2023-09-10 16:39 UTC
2. In Canvas, students have the ability to view a list of all of their classes so that they can navigate to class-specific discussions. This is an essential part of the layout of a course-management system, so it should be highly. prioritized.

**Comment by adityaganesh0309** [comment] 2023-09-10 17:04
Estimated Effort: 1 Day

Dependencies: Story #2 

Acceptance Criteria:
     - See a list of class in the classes section

**Comment by adityaganesh0309** [comment] 2023-09-26 21:41
Edit: This user story was a duplicate of one we newly created after changing our development plans.

**Comment by mingminggl** [comment] 2023-09-29 20:00
Students are now be able to see a list of their classes in the groups section

**Closed by mingminggl** 2023-09-29 20:00 UTC
Labels: feature
